Controllers films users
molestov/java-filmorate pull request #7
Opened 2023-02-23 15:14 UTC by molestov

2023-02-24 08:01 UTC, kalitva requested changes

2023-02-24 17:14 UTC, molestov commented on pom.xml
> +			<version>1.18.20</version>
С изначальной версией не проходит тесты на гитхабе.

2023-02-24 17:19 UTC, molestov commented on pom.xml
> +	<parent>
done

2023-02-24 17:19 UTC, molestov commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
done

2023-02-24 17:20 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
done

2023-02-24 17:20 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        while (films.containsKey(id)) {
done

2023-02-24 17:20 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == 0) {
done

2023-02-24 17:20 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId()) || film.getId() == 0) {
done

2023-02-24 17:20 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/model/Birthday.java
> +public @interface Birthday {
done

2023-02-24 17:21 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDateValidator.java
> +    public void initialize(ReleaseDate releaseDate) {}
done

2023-02-24 17:21 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDateValidator.java
> +        return releaseDate.isAfter(LocalDate.of(1895, 12, 28));
done

2023-02-24 17:21 UTC, molestov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
done

2023-02-24 17:21 UTC, molestov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .andExpect(status().is4xxClientError());
done

2023-02-24 17:21 UTC, molestov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .andExpect(status().is4xxClientError());
done

2023-02-24 17:22 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
done

2023-02-24 17:22 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ValidationException.java
> +public class ValidationException {
done

2023-02-24 17:22 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Birthday
done

2023-02-25 09:19 UTC, kalitva commented on pom.xml
> +			<version>1.18.20</version>
Окей, но на будущее знай, что в спринг-буте для многих зависимостей не следует переопределять версию

2023-02-25 09:25 UTC, kalitva approved these changes

2023-02-25 09:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UnknownIdExcerption.java
> +public class UnknownIdExcerption extends RuntimeException {
Excerption - поправь опечатку

2023-02-25 09:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDate.java
> +package ru.yandex.practicum.filmorate.model;
Создай пакет `validation` и положи туда `ReleaseDate` и `ReleaseDateValidator`

2023-02-25 09:25 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/ReleaseDateValidator.java
> +    @Override
Всегда пустая линия между блоком полей и объявлениями методов

https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace

2023-02-25 19:27 UTC, merged