TZ10 first commit
molestov/java-filmorate pull request #8
Opened 2023-03-20 18:05 UTC by molestov

2023-03-21 18:56 UTC, kalitva requested changes

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequestMapping("/films")
Верни обратно общий префикс, в методах нужно будет указывать оставшийся путь

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends = new HashSet<>();
`friends --> friendIds`

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.sort(new SortFilmsByLikesCountComparator());
Сортируй в стриме (метод `Stream#sorted`)

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return films.stream().limit(count).collect(Collectors.toList());
Форматируй стримы таким образом:

```
return films.stream()
        .limit(count)
        .collect(Collectors.toList());
```

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/SortFilmsByLikesCountComparator.java
> +public class SortFilmsByLikesCountComparator implements Comparator<Film> {
Лучше используй лямбду вместо явной реализации компаратора

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void removeFriends(int id, int friendId) {
`removeFriends --> removeFriend`

2023-03-21 18:56 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    public Map<Integer, User> getUsers();
Почему `Map`? Должен возвращаться список

2023-03-22 14:43 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return films.stream().limit(count).collect(Collectors.toList());
done

2023-03-22 14:57 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
done

2023-03-22 15:07 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName().isEmpty()) {
done

2023-03-22 17:10 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for(int i = 0; i < friends.size(); i++) {
done

2023-03-22 17:10 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> result = new ArrayList<>();
done

2023-03-23 14:23 UTC, kalitva approved these changes

2023-03-23 14:23 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void makeLike(int id, int userId) {
Лучше - `addLike`

2023-03-23 14:23 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id) == null) {
Результат вызова `filmStorage.getFilm(id)` лучше вынести в переменную (выделить выражение, затем нажать ctrl + alt + v)

2023-03-23 14:23 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> result = new ArrayList<>();
Лучше - 
```
return userStorage.getUser(id).getFriendIds()
        .stream()
        .map(userStorage::getUser)
        .collect(Collectors.toList())
```

2023-03-23 14:55 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id) == null) {
done

2023-03-23 14:57 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> result = new ArrayList<>();
done

2023-03-23 15:07 UTC, merged